### ISSUE TITLE
Refactor gulp workflow

### ISSUE THREAD

**Issue by mgallant-aptuitiv** [aptuitiv/generator-cacao-branchcms#24]
Due to a recent package update to `gulp-image` it is breaking our Gulp build scripts when updated. It seems as though the core of this issue is due to `gulp-image` being refactored into an ES module as of `6.3.0`. Since all of our Gulp scripts are written using CommonJS techniques we cannot include this package due to Node not allowing the mixing and matching of types. The ultimate solution would be to refactor our Gulp scripts as ES modules.

It looks like a bulk of the changes would just be to how we include libraries. We would need to switch from using `requires` to `import` syntax. We may also need to add `"type": "module"` to the package.json to indicate that this is an ES module instead of a CommonJS package.

https://pencilflip.medium.com/using-es-modules-with-commonjs-modules-in-node-js-1015786dab03

**Comment by erictompkins** [comment]
Another resource: [Pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)

**Comment by erictompkins** [comment]
This is done with 1.0.0 release
